spring:
  application:
    name: microservice-test-producer

  data:
    mongodb:
      host: octopus-mongodb-service
      port: 27017

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      topic-name: userUpdation



server:
  servlet:
    context-path: /producer/v1
  http2:
    enabled: true
  port: 8085
