spring:
  application:
    name: microservice-test-consumer

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: com.octopus.microservicetest1.model.*
      topic-name: userUpdation


  data:
    mongodb:
      port: 27017
      host: localhost
      database: octopus




server:
  servlet:
    context-path: /consumer/v1
  http2:
    enabled: true
  port: 9000

